name: Check signature requirements

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-signature-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check signature labels
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.pull_request.labels.some(label => label.name === 'no signature required' || label.name === 'signed')) {
              github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'success',
                context: 'Signature status',
                target_url: `https://github.com/${context.repo.repo}/actions/runs/${context.runId}`
              });
            } else {
            
              github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'pending',
                context: 'Signature status',
                target_url: `https://github.com/${context.repo.repo}/actions/runs/${context.runId}`
              });
            }
