name: Check signature requirements

on:
  pull_request_target:
    branches: [ "master" ]
    types: [labeled, unlabeled]

jobs:
  check-signature-labels:
    if: github.event.label.name == 'signed' || github.event.labe.name == 'no signature required'
    runs-on: ubuntu-latest
    steps:
      - name: Check signature labels
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            const state = context.eventName === 'labeled'? 'success': 'pending';
            const status = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: state,
              context: 'Signature check',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            }
            console.log(status)
            await github.rest.repos.createCommitStatus(status);
