name: Check signature requirements

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-signature-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check signature labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.UA_TOKEN }}
          script: |
            if (context.payload.pull_request.labels.some(label => label.name === 'no signature required' || label.name === 'signed')) {
              const status = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'error',
                context: 'Signature check',
                description: 'Check whether the PR is signed',
                target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
              }
              console.log('label found')
              console.log(status)
              const response = await github.rest.repos.createCommitStatus(status);
              console.log(response)
            } else {
              const status = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'pending',
                context: 'Signature check',
                description: 'Check whether the PR is signed',
                target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
              }
              console.log('label missing')
              console.log(status)
              const response = await github.rest.repos.createCommitStatus(status);
              console.log(response)
            }
